from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


PROJECT_ROOT = Path(__file__).resolve().parents[2]


class Settings(BaseSettings):
    app_name: str = "Vision Platform"
    app_env: str = "development"
    app_debug: bool = False
    app_host: str = "0.0.0.0"
    app_port: int = 9010
    database_url: str = "sqlite:///./data/vision_platform.db"
    database_pool_size: int = 10
    database_max_overflow: int = 20
    database_pool_recycle_seconds: int = 1800
    database_connect_timeout_seconds: int = 10
    embedding_storage_root: str = str(PROJECT_ROOT / "embeddings")
    harness_profile: str = "production"
    harness_config_path: str = "config/harness.json"
    harness_disabled_plugins: str = ""
    production_image_parallelism: int = 2
    production_roi_parallelism: int = 3
    production_vlm_parallelism: int = 3
    public_detect_success_code: int = 200
    scene_api_key: str = ""
    trusted_proxy_headers: bool = False
    smb_enabled: bool = False
    smb_server_root: str = r"\\caxaprdfile.catl.com\prd-file"
    smb_username: str = ""
    smb_password: str = ""
    smb_connection_timeout_seconds: float = 15.0
    vlm_secret_key: str = ""
    vlm_request_max_image_pixels: int = 1_003_520
    vlm_request_jpeg_quality: int = 90
    # Historical reference-vector data remains readable for record traceability.
    # No new DINOv2 reference vectors are generated by the current platform.
    reference_embedding_memory_cache_size: int = 512
    reference_similarity_scoring_mode: str = "ROBUST_TOP_K"
    reference_similarity_top_k: int = 3
    reference_similarity_top1_weight: float = 0.65
    automation_worker_enabled: bool = True
    automation_worker_poll_seconds: float = 2.0
    automation_worker_max_jobs_per_cycle: int = 1
    training_gpu_reserve_mb: int = 2048
    training_gpu_poll_seconds: float = 15.0
    training_artifacts_root: str = str(PROJECT_ROOT / "data" / "training_runs")
    training_default_workers: int = 2
    vision_model_storage_root: str = str(PROJECT_ROOT / "vision-models")
    image_alignment_enabled: bool = True
    image_alignment_max_shift_ratio: float = 0.05
    image_alignment_min_response: float = 0.08
    image_alignment_max_dimension: int = 1280
    image_alignment_anchor_search_margin_ratio: float = 0.35
    image_alignment_anchor_min_inliers: int = 8
    image_alignment_anchor_min_inlier_ratio: float = 0.35
    image_alignment_anchor_max_rotation_degrees: float = 8.0

    model_config = SettingsConfigDict(
        env_file=PROJECT_ROOT / ".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
